Draft of Objectives of the Project
kanishev2002/parallel-cpp-linalg pull request #1
Opened 2021-07-15 12:23 UTC by 0masiza0

2021-07-15 16:35 UTC, kanishev2002 requested changes

2021-07-15 16:35 UTC, kanishev2002 commented on README.md
> +* T **dot**(const T& a, const T& b) -- Dot product of two matrixes.
Думаю, что имеет смысл использовать не T, а Matrix< T > (здесь и в следующих пунктах), так как мы не хотим, чтобы нам давали что-то другое. Может быть даже создадим свой namespace для библиотеки, чтобы тип матрицы выделялся (что-нибудь вроде my_library::Matrix m;). Также матрицы во множественном числе будут matrices.

2021-07-15 16:35 UTC, kanishev2002 commented on README.md
> +* *TODO* **svd**(const T& a) -- Returns Singular Value Decomposition (three matrixes).
Matrices

2021-07-15 16:35 UTC, kanishev2002 commented on README.md
> +### Solving equations and inverting matrixes
И здесь тоже matrices))

2021-07-15 17:17 UTC, InfinityZxc requested changes

2021-07-15 17:17 UTC, InfinityZxc commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
натуральные и 0 даже можно в степень писать, -1,  если считаем это эквивалентом обратной

2021-07-15 17:22 UTC, kanishev2002 commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
Так ведь size_t и есть натуральные и 0. Или претензия к тексту?

2021-07-15 17:25 UTC, InfinityZxc commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
про 0 к тексту, а если -1 то и тип другой нужен

2021-07-15 17:40 UTC, 0masiza0 commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
Думаю, -1 степень лучше не использовать, а пользоваться inv(a), потому что иначе будет сложнее отсечь попытки пользователя возводить матрицу в отрицательные степени. 0 в англоязычной литературе обычно включён в натуральные числа, но здесь я уточню в тексте.

2021-07-15 18:16 UTC, InfinityZxc commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
мы то понимаем что это inv(a) под капотом будет, а как же не столь преосвященный пользователь, желающий найти -1 степень. отсекать попытки можно одним ифом, так что норм наверное

2021-07-15 18:47 UTC, 0masiza0 commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
IMHO такому пользователю лучше дать код, который с некорректными аргументами просто не скомпилируется. Плюс, бросаться исключениями дорого по ресурсам.

2021-07-15 18:53 UTC, InfinityZxc commented on README.md
> +* T **matrix_power**(const T& a, size_t n) -- Raise a square matrix to the (natural) power n.
аргумент, но тогда в этом месте мы говорим undefined behavior

2021-07-15 19:40 UTC, InfinityZxc approved these changes

2021-07-18 10:08 UTC, kanishev2002 approved these changes

2021-07-18 10:08 UTC, merged