Add Matrix power and fix some issues in Matrix.h/.cpp
kanishev2002/parallel-cpp-linalg pull request #13
Opened 2021-07-20 13:59 UTC by 0masiza0

2021-07-20 14:10 UTC, kanishev2002 commented on src/matrix_power/matrix_power.cpp
> +Matrix<T> matrix_power(const Matrix<T>& a, size_t n) {
По-моему какая-то сложная и неочевидная реализация. Почему бы не сделать [как на емаксе](http://e-maxx.ru/algo/export_binary_pow)?

2021-07-20 15:49 UTC, InfinityZxc approved these changes

2021-07-20 17:29 UTC, InfinityZxc requested changes

2021-07-20 17:29 UTC, InfinityZxc commented on src/matrix_power/matrix_power.cpp
> +template<typename T>
неть мьютекса

2021-07-21 10:22 UTC, 0masiza0 commented on src/matrix_power/matrix_power.cpp
> +Matrix<T> matrix_power(const Matrix<T>& a, size_t n) {
Переделано

2021-07-21 10:22 UTC, 0masiza0 commented on src/matrix_power/matrix_power.cpp
> +template<typename T>
Сейчас добавлю

2021-07-21 10:44 UTC, kanishev2002 approved these changes

2021-07-21 17:28 UTC, InfinityZxc commented on src/matrix_power/matrix_power.cpp
> +  std::shared_lock<Matrix<T>>(a.shared_mtx_);
какая-то странная форма  объявления лока, оно вообще компилится будет(без учета нынешней недоступности мьютекса)?

2021-07-22 10:52 UTC, kanishev2002 commented on src/matrix_power/matrix_power.cpp
> +  std::shared_lock<Matrix<T>>(a.shared_mtx_);
Действительно, по идее должно быть либо <shared_mutex> либо просто ничего не писать в угловых скобках.

2021-07-22 20:09 UTC, InfinityZxc commented on src/Matrix_Power/Matrix_Power.cpp
> +  std::shared_lock(a.shared_mtx_);
все еще не уверен, что так можно

2021-07-22 20:10 UTC, InfinityZxc commented
я могу понять почему конфликт файлов в .срр, но почему он еще в .h?

2021-07-23 09:00 UTC, 0masiza0 commented on src/Matrix_Power/Matrix_Power.cpp
> +  std::shared_lock(a.shared_mtx_);
Можно, если shared_mtx_ будет доступен в matrix_power. Компилятор не ругается

2021-07-23 09:02 UTC, 0masiza0 commented
> я могу понять почему конфликт файлов в .срр, но почему он еще в .h?

Возможно из-за путаницы в \#include с заглавными/строными буквами

2021-07-23 21:38 UTC, InfinityZxc commented on src/Matrix_Power/Matrix_Power.cpp
> +  std::shared_lock(a.shared_mtx_);
у переменной имени нет, у меня ругается на такой формат

2021-07-31 20:29 UTC, kanishev2002 requested changes

2021-07-31 20:29 UTC, kanishev2002 commented on src/Matrix_Power/Matrix_Power.cpp
> +  std::shared_lock(a.shared_mtx_);
Все таки давай поменяем на переменную с именем.

2021-07-31 20:29 UTC, kanishev2002 commented on src/Matrix_Power/Matrix_Power.cpp
> +#include "../../include/Matrix_Power.h"
Нужно поменять, чтобы соответствовало нашим правилам названия – файлы с маленькой буквы, функции – с большой.

2021-07-31 20:29 UTC, kanishev2002 commented on src/Matrix_Power/Matrix_Power.cpp
> +#include "../../include/Dot.h"
И здесь

2021-07-31 20:29 UTC, kanishev2002 commented on src/Matrix_Power/Matrix_Power.cpp
> +      result = dot(result, tmp);
```suggestion
      result = Dot(result, tmp);
```

2021-07-31 20:29 UTC, kanishev2002 commented on src/Matrix_Power/Matrix_Power.cpp
> +      tmp = dot(tmp, tmp);
```suggestion
      tmp = Dot(tmp, tmp);
```

2021-09-01 17:40 UTC, merged