Implemented Matrix Det, added Fraction, namespace Equation and Thread…
kanishev2002/parallel-cpp-linalg pull request #18
Opened 2021-07-24 15:38 UTC by 0masiza0

…Pool

2021-07-24 22:50 UTC, InfinityZxc requested changes

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +                    denom_ * other.denom_);
Потенциальное переполнение

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    denom_ *= other.denom_;
Переполнение

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    return Fraction(num_ * other.denom_, denom_ * other.num_);
Переполнение

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +}
Нам этот оператор кроме как для отладки нужен? Если это открыто использоваться не будет

2021-07-24 22:50 UTC, InfinityZxc commented on src/thread_pool.cpp
> +    throw std::invalid_argument("Number of threads equals zero\n");
У hardware_concurrency написано The value should be considered only a hint. А 0, оно возвращает в любой непонятной ситуации, так что не уверен, что здесь стоит кидать сразу исключение

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    if (b == T(0))
Вроде нейтральный по сложению элемент можно и Т() взять, аналогично далее

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    denom = (denom > T(0) ? denom : -denom) / gcd;
А в этих 3 строчках мы вообще предполагаем что есть оператор сравнения, хотя этого ранее не требовали

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    return Fraction(num_ * other.num_, denom_ * other.denom_);
Угадайте что

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    denom_ *= other.denom_;
Верно,

2021-07-24 22:50 UTC, InfinityZxc commented on src/fraction.cpp
> +    return Fraction(t) + fraction;
Я может не заметил, но нет конструктора от одной переменной

2021-07-25 09:17 UTC, 0masiza0 commented on src/fraction.cpp
> +}
Если этот класс нужен только нам, то да, только для отладки. А так с помощбю него удобно выводить матрицу дробей в одну строку.

2021-07-25 09:19 UTC, 0masiza0 commented on src/thread_pool.cpp
> +    throw std::invalid_argument("Number of threads equals zero\n");
std::thread::hardware_concurrency() -- это значение для threads по умолчанию, но пользователь может руками передать в конструктор 0. И вроде мы должны отказываться с этим работать.

2021-07-25 09:24 UTC, 0masiza0 commented on src/fraction.cpp
> +    return Fraction(t) + fraction;
Он не нужен, так как конструктор присваивает полям num_ и denom_ значения по умолчанию. Если передать только одну переменную a, он создаст дробь a/1, если ничего не передавать -- 0/1.

2021-07-25 09:28 UTC, 0masiza0 commented on src/fraction.cpp
> +    if (b == T(0))
Мне кажется, что лучше явно указывать, аналог какого числа мы хотим получить, чтобы не путать с нейтральным по умножению и т.п.

2021-07-25 09:30 UTC, 0masiza0 commented on src/fraction.cpp
> +    denom = (denom > T(0) ? denom : -denom) / gcd;
Я не знаю, как иначе получить модуль числа без std::abs.

2021-07-25 18:31 UTC, InfinityZxc commented on src/fraction.cpp
> +    if (b == T(0))
У нас вообще нет гарантий, что 0,1,-1 дают то, что мы хотим

2021-07-26 09:44 UTC, 0masiza0 commented on src/fraction.cpp
> +    if (b == T(0))
Кстати, если мы хотим работать с векторными пространствами, то T вообще обязан быть полем. Так что, вероятно, придётся вообще где-то указать это требование и не работать с int, size_t и прочими. Тогда Fraction не нужен. Но есть вопрос о том, как сравнивать вещественные числа. Надо определить погрешность какую-то, потому что иначе два по идее равных числа рискуют не пройти x == y.

2021-07-26 09:46 UTC, 0masiza0 commented on src/fraction.cpp
> +    if (b == T(0))
Но если мы требуем, чтобы T был полем, то 0, 1 и -1 гарантированно работают так, как надо

2021-07-31 19:07 UTC, kanishev2002 requested changes

2021-07-31 19:27 UTC, kanishev2002 commented on src/equation/equation.cpp
> +int Equation::compose_rows<typename T>(const std::vector<T>& row1, const std::vector<T>& row2) {
Только что заметил. Что здесь int делает? И вообще какая-то странная форма написания шаблонной функции.

2021-07-31 19:27 UTC, kanishev2002 commented on src/equation/equation.cpp
> +int Equation::multiply_by_scalar(const std::vector<T>& row, const T& scalar) {
Опять таки не int, а std::vector<T> наверное.

2021-07-31 19:32 UTC, kanishev2002 commented on src/det/det.cpp
> +            auto coef = -matrix[i][non_zero_column] / matrix[cur_row][non_zero_column];
А вот тут не нужно ли захватывать cur_row, cur_column, и т.д.? Вроде мы их меняем в 57-й строке.

2021-07-31 19:45 UTC, kanishev2002 commented on src/equation/equation.cpp
> +int Equation::multiply_by_scalar(const std::vector<T>& row, const T& scalar) {
Сам спросил - сам починил

2021-07-31 19:46 UTC, kanishev2002 commented on src/equation/equation.cpp
> +int Equation::compose_rows<typename T>(const std::vector<T>& row1, const std::vector<T>& row2) {
Fixed

2021-07-31 19:46 UTC, kanishev2002 commented on src/det/det.cpp
> +            auto coef = -matrix[i][non_zero_column] / matrix[cur_row][non_zero_column];
Вот этот вопрос все еще остался

2021-08-02 11:23 UTC, 0masiza0 commented on src/det/det.cpp
> +            auto coef = -matrix[i][non_zero_column] / matrix[cur_row][non_zero_column];
Да, нужно. Поправлю

2021-08-02 11:29 UTC, 0masiza0 commented on src/fraction.cpp
> +                    denom_ * other.denom_);
Нет класса -- нет проблемы:p
Аналогично в других комментариях про переполнение

2021-08-03 09:34 UTC, kanishev2002 requested changes

2021-08-03 09:34 UTC, kanishev2002 commented on src/det/det.cpp
> +          matrix[i] = Equation::compose_rows(
Я тут вот что подумал: мы же получается делаем много лишнего копирования, когда делаем сначала multiply_by_scalar, а потом сразу compose_rows. И вроде как в линейной алгебре у нас эта операция обозначалась, как прибавить к строке другую строку, умноженную на скаляр. Предлагаю добавить в compose rows дополнительный параметр, который отвечает за скаляр, на который умножаем. Тогда будет минимум копирования при такой операции

2021-08-03 17:57 UTC, 0masiza0 commented on src/det/det.cpp
> +          matrix[i] = Equation::compose_rows(
Вроде как тут один и тот же объект (строка) перебрасывается между функциями, а создаётся один раз в multiply_by_scalar. Если это не так, поправьте меня. Твоё предложение всё равно ускорит программу (будет, как минимум, меньше проходов по векторам), но я не знаю, сильная ли это оптимизация. Но можно всё равно доп. параметр добавить

2021-08-04 08:56 UTC, kanishev2002 commented on src/det/det.cpp
> +          matrix[i] = Equation::compose_rows(
Ну мы же в multiply создаем копию под названием result, потом ее возвращаем (что, возможно, тоже приводит к копированию), потом в compose rows создаем еще один result, т.е. по сути, снова копируем. Если сделать, как я предлагаю, то можно создавать только тот result, который в compose_rows. Не знаю, сколько именно копирований мы сократим таким образом, но как минимум одно точно.

2021-08-04 09:04 UTC, kanishev2002 reviewed
В общем, я написал предложения, как я думаю это сделать

2021-08-04 09:04 UTC, kanishev2002 commented on src/equation/equation.cpp
> +    result.emplace_back(row1[i] + row2[i]);
```suggestion
    result.emplace_back(row1[i] + coef * row2[i]);
```

2021-08-04 09:04 UTC, kanishev2002 commented on src/det/det.cpp
> +              Equation::multiply_by_scalar(matrix[cur_row], coef), matrix[i]);
```suggestion
          matrix[i] = Equation::compose_rows(matrix[i], matrix[cur_row], coef);
```

2021-08-04 09:18 UTC, merged