Implemented Matrix Trace
kanishev2002/parallel-cpp-linalg pull request #23
Opened 2021-08-02 15:06 UTC by 0masiza0

2021-08-02 15:28 UTC, InfinityZxc requested changes

2021-08-02 15:28 UTC, InfinityZxc commented on src/trace/trace.cpp
> +  T result = T(0);
мне не нравится этот Т(0) всё ещё, конструктор по умолчанию лучше мне кажется

2021-08-02 15:28 UTC, InfinityZxc commented on src/trace/trace.cpp
> +T Trace(const Matrix<T>& a) {
читабельное название переменных я так понимаю это не наша прерогатива

2021-08-02 15:28 UTC, InfinityZxc commented on src/trace/trace.cpp
> +    threads.emplace_back([&, i, rows = rows](auto begin, auto end) {
зачем нам тут rows?

2021-08-03 16:43 UTC, 0masiza0 commented on src/trace/trace.cpp
> +  T result = T(0);
Ок, но что делать с конструктором единицы?

2021-08-03 16:43 UTC, 0masiza0 commented on src/trace/trace.cpp
> +T Trace(const Matrix<T>& a) {
Я беру шапки функций из нашего TODO листа в README. Так как мы его согласовали, то why not

2021-08-03 16:44 UTC, 0masiza0 commented on src/trace/trace.cpp
> +    threads.emplace_back([&, i, rows = rows](auto begin, auto end) {
Остался от прошлой версии кода. Уберу

2021-08-25 10:44 UTC, kanishev2002 approved these changes

2021-09-01 17:41 UTC, merged