Implemented Parallel and Singular Matrix Eig
kanishev2002/parallel-cpp-linalg pull request #26
Opened 2021-08-15 09:39 UTC by 0masiza0

2021-08-17 11:04 UTC, kanishev2002 commented on src/eig/eig.cpp
> +std::vector<std::vector<T>> SolveMultipleSolutions(Matrix<T>&& a, const T& delta) {
Не до конца понял, что же делает эта функция

2021-08-17 11:04 UTC, kanishev2002 commented on src/eig/eig_singular.cpp
> +                break;
Здесь же можно просто сделать return false и вроде как избавиться от is_up_tr

2021-08-17 13:32 UTC, 0masiza0 commented on src/eig/eig.cpp
> +std::vector<std::vector<T>> SolveMultipleSolutions(Matrix<T>&& a, const T& delta) {
Находит ФСР однородной системы, где решений бесконечно много. Функция Solve работает только с системами уравнений, имеющими единственное решение, поэтому потребовалось писать ещё одну функцию.

2021-08-17 13:37 UTC, 0masiza0 commented on src/eig/eig_singular.cpp
> +                break;
А, да, можно. Ок

2021-08-17 13:38 UTC, 0masiza0 commented on src/eig/eig.cpp
> +        ThreadPool pool;
Ага, переделаю

2021-08-19 03:42 UTC, InfinityZxc requested changes

2021-08-19 03:42 UTC, InfinityZxc commented on src/eig/eig.cpp
> +          result[row][j] = -a[i][column];
здесь и ниже похоже на reduce проблему

2021-08-23 16:59 UTC, kanishev2002 commented on include/eig.h
> +#include "Matrix.h"
Компилятор жалуется, надо matrix.h

2021-08-23 16:59 UTC, kanishev2002 commented on include/eig_singular.h
> +#include "Matrix.h"
Здесь тоже matrix.h

2021-08-23 16:59 UTC, kanishev2002 commented on src/eig/eig_singular.cpp
> +
В этом файле нужно тоже подключить cmath

2021-08-25 10:34 UTC, kanishev2002 approved these changes

2021-08-25 12:34 UTC, merged