Implemented Matrix Inv
kanishev2002/parallel-cpp-linalg pull request #27
Opened 2021-08-23 13:46 UTC by 0masiza0

2021-08-23 16:41 UTC, kanishev2002 requested changes

2021-08-23 16:41 UTC, kanishev2002 commented on src/inv.cpp
> +#include "../../include/inv.h"
первые `..` лишние по идее

2021-08-23 16:41 UTC, kanishev2002 commented on src/inv.cpp
> +#include "solve.h"
Это, насколько я понимаю мы еще не смерджили. Надо бы все равно указать полный путь. Вряд ли мы его поменяем.

2021-08-25 10:35 UTC, 0masiza0 commented on src/inv.cpp
> +#include "../../include/inv.h"
Я просто забыл положить inv.cpp в соответствующую папку. Исправляю

2021-08-25 10:38 UTC, kanishev2002 approved these changes

2021-08-25 10:41 UTC, kanishev2002 commented on src/inv/inv.cpp
> +#include "../../include/inv.h"
```suggestion
#include <include/inv.h>
```

2021-08-25 10:41 UTC, kanishev2002 commented on src/inv/inv.cpp
> +#include "../../include/solve.h"
```suggestion
#include <include/solve.h>
```

2021-08-25 10:41 UTC, kanishev2002 commented on src/inv/inv.cpp
> +#include "../../include/solve.h"
Думаю, что вот так все-таки лучше

2021-08-25 10:53 UTC, 0masiza0 commented on src/inv/inv.cpp
> +#include "../../include/solve.h"
Но мы же всё это время делали по-другому. Без ../../ вообще будет работать?

2021-08-25 12:34 UTC, merged