scuffed print and <<
kanishev2002/parallel-cpp-linalg pull request #3
Opened 2021-07-16 01:17 UTC by InfinityZxc

2021-07-16 11:10 UTC, kanishev2002 requested changes

2021-07-16 11:10 UTC, kanishev2002 commented on Matrix/Matrix.cpp
> +    auto compare_vectors = [&](const auto &row1, const auto &row2) {
Обновите стайлгайд, как я написал в телеграме

2021-07-16 11:10 UTC, kanishev2002 commented on Matrix/Matrix.cpp
> +            out << matrix_[i][j] << '\t';
Вроде обсуждали, что может быть нужен мьютекс

2021-07-17 10:37 UTC, 0masiza0 requested changes

2021-07-17 13:10 UTC, kanishev2002 commented on Matrix/Matrix.cpp
> +        out << '\n';
Починил

2021-07-17 13:11 UTC, kanishev2002 commented on Matrix/Matrix.cpp
> +        for (size_t j = 0; j < matrix_[0].size(); ++j) {
Сделал

2021-07-17 13:12 UTC, kanishev2002 commented on Matrix/Matrix.h
> +
Поменял spliter на separator. Символы пока оставил

2021-07-17 13:13 UTC, merged